name                         = "hashicups"
region                       = "us-west-2"
boundary_endpoint            = "<get from infrastructure outputs>"
boundary_kms_recovery_key_id = "<get from infrastructure outputs>"
ecs_cluster                  = "<get from infrastructure outputs>"
product_database_address     = "<get from infrastructure outputs>"
